server:
  port: 8080

spring:
  application:
    name: SimpleCrud


  datasource:
    url: jdbc:mysql://localhost:3306/simple_crud?createDatabaseIfNotExist=true
    username: root
    password: Fanap2226!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
